import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
    { id: 'p1', name: 'SUPERBOX PO', category: 'Zasadowy proszek do mycia karoserii', image: '/assets/products/superbox-po.png', description: 'Skutecznie usuwa wszelkie zanieczyszczenia i zapobiega tworzeniu się kamienia na urządzeniach. Dzięki swojemu składowi umożliwia wytworzenie kontrolowanej piany zarówno w gorącej, jak i w ciepłej wodzie.', features: ['produkt zasadowy'], specs: { temp: 40, dilution: '-', isEco: false, ph: 12 }, price: 257, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 257 }] },
    { id: 'p2', name: 'SUPERCREAM', category: 'Szampon do mycia karoserii', image: '/assets/products/supercream.png', description: 'Intensywnie myjący, skoncentrowany produkt do mycia karoserii pojazdów. Wyjątkowo skuteczny, mocno pieniący się. Idealny do usuwania najtrudniejszych zabrudzeń, przywraca blask czyszczonej powierzchni.', features: ['produkt silnie pieniący'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 410, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 410 }] },
    { id: 'p3', name: 'SUPERFOAM ACTIVE', category: 'Piana aktywna', image: '/assets/products/superfoam-active.png', description: '', features: ['produkt silnie pieniący'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 520, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 520 }] },
    { id: 'p4', name: 'SHINE DIAMANT', category: 'Wosk nabłyszczająco-osuszający', image: '/assets/products/shine-diamant.png', description: 'Wysokiej jakości wosk przeznaczony zarówno do samochodów osobowych, jak i ciężarowych. Silnie skoncentrowany, uszczelniający powierzchnię i chroniący ją wosk. Nie zawiera silikonu, rozpuszczalników na bazie węglowodoru czy olejów mineralnych. Nadaje długotrwały blask i połysk.', features: ['wysoka wydajność', 'bezpieczeństwo'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 640, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '22 kg', price: 640 }] },
    { id: 'p5', name: 'TRANSNET MECA-SUP', category: 'Pieniący się odtłuszczacz do części mechanicznych', image: '/assets/products/transnet-meca-sup.png', description: 'Skoncentrowany, pieniący się, zasadowy środek do usuwania sadzy, osadów po spalaniu itp. Przeznaczony do części mechanicznych, podwozi, karoserii plandek. Może być stosowany na gorąco.', features: ['produkt silnie pieniący', 'produkt zasadowy'], specs: { temp: 50, dilution: '-', isEco: false, ph: 13 }, price: 450, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 450 }] },
    { id: 'p6', name: 'OXYD-TN05090', category: 'Kwasowy renowator do usuwania rdzy', image: '/assets/products/oxyd-tn05090.png', description: 'Środek czyszczący na bazie kwasu, usuwający rdzę i kamień. Produkt pieniący się, skutecznie czyści kontenery kolejowe i drogowe oraz posadzki w chłodniach. Przeznaczony do aluminium: felg, szyn, cystern itp. Odpowiedni również do stali ocynkowanej i usuwania zabrudzeń cementowych.', features: ['produkt kwasowy', 'niskie PH', 'produkt silnie pieniący'], specs: { temp: 20, dilution: '-', isEco: false, ph: 2 }, price: 600, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 600 }] },
    { id: 'p7', name: 'TRANSNET FOAM', category: 'Piana do mycia karoserii', image: '/assets/products/transnet-foam.png', description: 'Mocno skoncentrowany szampon o właściwościach antystatycznych. Zrównoważona kombinacja różnych środków powierzchniowo czynnych pozwala na generowanie kontrolowanej piany. Zapobiega osadzaniu się kamienia na urządzeniach. Charakteryzuje się doskonałą spłukiwalnością przy minimalnej ilości zimnej lub ciepłej wody. Przeznaczony do czyszczenia karoserii pojazdów, szczególnie skuteczny w usuwaniu owadów, śladów węglowodorów i innych zanieczyszczeń.', features: ['produkt silnie pieniący', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 660, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '26 kg', price: 660 }] },
    { id: 'p8', name: 'PULVE 8', category: 'Profesjonalny opryskiwacz', image: '/assets/products/pulve-8.png', description: 'Profesjonalny opryskiwacz PULVE LASER specjalnie przystosowany do pracy z kwasami, wykonany z polipropylenu. Może być także wykorzystywany do aplikacji środków owadobójczych, myjących, przeznaczonych do usuwania zanieczyszczeń z maszyn budowlanych i pojazdów przemysłowych.', features: ['produkt kwasowy', 'bezpieczeństwo'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 900, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '8 l', price: 900 }] },
    { id: 'p9', name: 'PERLE', category: 'Wysokiej jakości środek osuszający', image: '/assets/products/perle.png', description: 'Wysokiej jakości środek osuszający do stosowania na samochodach osobowych, ciężarowych, jak i w pojazdach transportu publicznego. Mocno skoncentrowany, zabezpiecza przed wodą. Nie zawiera silikonu i nie wymaga spłukiwania po umyciu. Tworzy na powierzchni niewidoczny hydrofobowy film, który odpycha cząsteczki wody. Pozwala uniknąć powstawania białych śladów i osadzania się kropelek wody oraz optymalizuje proces mycia i osuszania.', features: ['wysoka wydajność', 'bezpieczeństwo'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 520, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 520 }] },
    { id: 'p10', name: 'C SUPER', category: 'Szampon o wzmocnionym działaniu', image: '/assets/products/c-super.png', description: 'Skoncentrowany szampon o właściwościach antystatycznych. Skuteczny w usuwaniu smarów i owadów. Działa dobrze nawet bez szorowania. Usuwa film drogowy. Przeznaczony do myjni portalowych, pianownic, itp.', features: ['wysoka wydajność', 'do mycia automatycznego'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 145, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '5 kg', price: 145 }, { name: '25 kg', price: 600 }, { name: '240 kg', price: 4900 }, { name: '1150 kg', price: 15000 }] },
    { id: 'p11', name: 'C NATURE', category: 'Szampon z certyfikatem ECOCERT, neutralne pH', image: '/assets/products/c-nature.png', description: 'Skoncentrowany szampon do samochodów, opracowany na bazie odnawialnych składników, pozyskanych w sposób przyjazny dla środowiska. W pełni spełnia wymagania określone przez ECOCERT.', features: ['certyfikat ECO CERT', 'ekologiczny', 'bezpieczeństwo'], specs: { temp: 20, dilution: '-', isEco: true, ph: 7 }, price: 620, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 620 }, { name: '210 kg', price: 5160 }] },
    { id: 'p12', name: 'FROZEN', category: 'Szampon do stosowania w niskich temperaturach', image: '/assets/products/frozen.png', description: 'Mocny, pieniący się szampon do mycia samochodów ciężarowych, zadaniowych itp. Skutecznie usuwa ślady węglowodorów, smarów, ziemi i soli. Dzięki połączeniu czynników maskujących, soli mineralnych i środków powierzchniowo czynnych, można go stosować aż do temperatury -20°C.', features: ['produkt silnie pieniący', 'wysoka wydajność'], specs: { temp: -20, dilution: '-', isEco: false, ph: 8 }, price: 420, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 420 }, { name: '240 kg', price: 3900 }] },
    { id: 'p13', name: 'IRIDIUM', category: 'Mocny szampon myjący', image: '/assets/products/iridium.png', description: 'Mocno skoncentrowany szampon samochodowy dla profesjonalistów. Wyjątkowa formuła, która łatwo usuwa film drogowy i różne plamy (owady, smary, olej itp.). Dzięki specjalnej formule, działa bardzo szybko na karoserii, a także na plandekach, przyczepach ciężarówek, maszynach budowlanych, transporcie publicznym itp.', features: ['wysoka wydajność', 'produkt silnie pieniący'], specs: { temp: 20, dilution: '-', isEco: false, ph: 9 }, price: 400, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '20 kg', price: 400 }, { name: '200 kg', price: 3700 }] },
    { id: 'p14', name: 'PLATINIUM', category: 'Szampon klasy premium', image: '/assets/products/platinium.png', description: 'Szampon do karoserii o wzmocnionych właściwościach myjących. Wszechstronny – może być stosowany w myjniach portalowych lub samoobsługowych. Skutecznie usuwa film drogowy i różne zabrudzenia. Szybko działa na karoserii, a także na plandekach, przyczepach, środkach transportu publicznego, itp. Łatwo się spłukuje. Biodegradowalność i optymalne bezpieczeństwo.', features: ['wysoka wydajność', 'ekologiczny', 'bezpieczeństwo'], specs: { temp: 20, dilution: '-', isEco: true, ph: 8 }, price: 4500, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '220 kg', price: 4500 }] },
    { id: 'p15', name: 'TRANSNET MECA-D', category: 'Niepieniący się odtłuszczacz do części mechanicznych', image: '/assets/products/transnet-meca-d.png', description: 'Mocny środek czyszczący i odtłuszczający, może być stosowany na gorąco. Niepieniący się, przemysłowy preparat alkaliczny do warsztatów. Skuteczny na tłustych podłogach, częściach mechanicznych, silnikach wyjętych z obudowy, a także do czyszczenia felg.', features: ['produkt nie pieniący', 'produkt zasadowy', 'wysokie PH'], specs: { temp: 60, dilution: '-', isEco: false, ph: 13 }, price: 600, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 600 }] },
    { id: 'p16', name: 'TRUCK R', category: 'Szampon do stosowania w niskich temperaturach', image: '/assets/products/truck-r.png', description: 'Mocny, pieniący się szampon do mycia samochodów ciężarowych. Przeznaczony do stosowania w okresie zimowym, usuwa smary oraz wszelkie zanieczyszczenia powstałe podczas jazdy. Świetnie sprawdza się jako odtłuszczacz do mycia plandek, kontenerów, maszyn rolniczych.', features: ['produkt silnie pieniący', 'wysoka wydajność'], specs: { temp: 0, dilution: '-', isEco: false, ph: 8 }, price: 480, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 480 }, { name: '250 kg', price: 3600 }] },
    { id: 'p17', name: 'S+', category: 'Szampon zapachowy', image: '/assets/products/s+.png', description: 'Szampon nowej generacji do wszystkich pojazdów. Usuwa brud drogowy, pozostawiając błyszczący film na karoserii pojazdu.', features: ['wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 422, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 422 }] },
    { id: 'p18', name: 'B', category: 'Środek do usuwania betonu', image: '/assets/products/b.png', description: 'Silnie stężony produkt do usuwania betonu na bazie mieszanki silnych kwasów. Specjalnie opracowany do stosowania jako produkt czyszczący w zakładach produkcji betonu. Usuwa kamień, zaczyn cementowy i osady z kamienia na urządzeniach myjących czy pojazdach.', features: ['produkt kwasowy', 'niskie PH', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 1.5 }, price: 350, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 350 }, { name: '240 kg', price: 3000 }] },
    { id: 'p19', name: 'HT2002 P+', category: 'Skoncentrowany produkt do usuwania kamienia', image: '/assets/products/ht2002-p+.png', description: 'Ultraskoncentrowany renowator kwasowy, gotowy do użycia. Czyści sprzęt zabrudzony wapnem, kredą, cementem, żużlem itp. Odpowiedni do niskiego i wysokiego ciśnienia.', features: ['produkt kwasowy', 'niskie PH', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 1 }, price: 320, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 320 }] },
    { id: 'p20', name: 'DEG 3', category: 'Produkt do usuwania smoły', image: '/assets/products/deg-3.png', description: 'Przeznaczony do silników i części mechanicznych rozpuszczalnik w formie emulsji do usuwania smoły. Zawartość składników powierzchniowo-czynnych sprawia, że preparat ten jest wyjątkowo skuteczny w walce z osadami smaru i zabrudzeniami ropą.', features: ['wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 720, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '20 kg', price: 720 }] },
    { id: 'p21', name: 'ANTICOLBIO F', category: 'Chemia specjalistyczna', description: '', features: [], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 704, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '20 l', price: 704 }] },
    { id: 'p22', name: 'DEBIO BIO', category: 'Chemia specjalistyczna', description: '', features: [], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 1659, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '30 l', price: 1659 }] },
    { id: 'p23', name: 'AF', category: 'Niskopieniący odtłuszczacz z jakością spożywczą', image: '/assets/products/af.png', description: 'Bardzo silny alkaliczny odtłuszczacz do czyszczenia wnętrz ciężarówek i cystern spożywczych. Niskopieniący się detergent o wysokiej zwilżalności, odpowiedni do czyszczenia zbiorników i usuwania olejów, takich jak rzepakowy, palmowy, słonecznikowy.', features: ['produkt nie pieniący', 'jakość spożywcza', 'produkt zasadowy', 'wysokie PH'], specs: { temp: 20, dilution: '-', isEco: false, ph: 13 }, price: 275, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '25 kg', price: 275 }] },
    { id: 'p24', name: 'NEUTRALODOR', category: 'Środek do usuwania zapachów', image: '/assets/products/neutralodor.png', description: 'Bardzo skoncentrowany środek do usuwania zapachów. Do stosowania w wnętrzach chłodni samochodów, cystern spożywczych, kontenerów na śmieci, przechowywania materiałów gnijących, oczyszczalniach ścieków itp. Nie pozostawia zapachu po użyciu.', features: ['niwelowanie zapachów', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 1400, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '24 kg', price: 1400 }] },
    { id: 'p25', name: 'OD', category: 'Środek do usuwania zapachów', image: '/assets/products/od.png', description: 'Bardzo skoncentrowany środek do usuwania zapachów. Do stosowania w wnętrzach chłodni samochodów, cystern spożywczych, kontenerów na śmieci, przechowywania materiałów gnijących, oczyszczalniach ścieków itp. Nie pozostawia zapachu po użyciu.', features: ['niwelowanie zapachów', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 274, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '4 kg', price: 274 }] },
    { id: 'p26', name: 'VITRE', category: 'Środek do szkła i tworzyw sztucznych', image: '/assets/products/vitre.png', description: 'Środek czyszcząco-odtłuszczający do powierzchni szklanych i tworzyw sztucznych. Nie powoduje korozji czyszczonej powierzchni, nie pozostawia śladów ani zacieków po zastosowaniu. Produkt można stosować na powierzchniach mających kontakt z żywnością.', features: ['bezpieczeństwo', 'jakość spożywcza'], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 95, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '5 kg', price: 95 }] },
    { id: 'p27', name: 'TS 3274', category: 'Przemysłowy detergent do podłóg', image: '/assets/products/ts-3274.png', description: 'Odtłuszczający, niepieniący się detergent na bazie naturalnych rozpuszczalników. Przeznaczony do podłóg betonowych, żywicznych, asfaltowych oraz kafelków podłogowych. Usuwa ślady kół pozostawione przez wózki widłowe itp. Pozostawia długotrwały zapach.', features: ['produkt nie pieniący', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 130, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '5 kg', price: 130 }, { name: '24 kg', price: 500 }] },
    { id: 'p28', name: 'TS', category: 'Przemysłowy detergent do podłóg', description: 'Odtłuszczający, niepieniący się detergent na bazie rozpuszczalników. Przeznaczony do podłóg betonowych, żywicznych, asfaltowych oraz kafelków podłogowych. Usuwa ślady kół pozostawione przez wózki widłowe itp. Pozostawia długotrwały zapach.', features: ['produkt nie pieniący', 'wysoka wydajność'], specs: { temp: 20, dilution: '-', isEco: false, ph: 8 }, price: 97, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '5 kg', price: 97 }] },
    { id: 'p29', name: 'Pompa dozująca Translav CAR PRO / ACID', category: 'Urządzenia', image: '/assets/products/pompa-dozujaca-translav-car-pro-acid.png', description: 'Translav CAR PRO jest urządzeniem pozwalającym na rozpylenie i natryskiwanie uprzednio przygotowanego produktu na powierzchnie przeznaczone do mycia. Translav jest wyposażony w wąż, lancę oraz dysze dozujące, niezbędne do prawidłowego działania sprzętu.', features: [], specs: { temp: 20, dilution: '-', isEco: false, ph: 7 }, price: 1550, quantity: 1, discount: 0, maxDiscount: 25, variants: [{ name: '1 szt.', price: 1550 }] },
];

export const MOCK_SALES_REPS: import('./types').SalesRep[] = [
    { name: "Florkowski Jacek", phone: "+48 602 175 962", email: "jacek.florkowski@orapi.com" },
    { name: "Główczyk Janusz", phone: "+48 726 668 361", email: "jasjanusz@interia.pl" },
    { name: "Karwowski Ireneusz", phone: "+48 786 676 079", email: "i.karwowski.orapi@gmail.com" },
    { name: "Korzeniewski Bartosz", phone: "+48 696 197 600", email: "bartek.korzeniewski@orapi.com.pl" },
    { name: "Lasota Tomasz", phone: "+48 505 284 326", email: "tom.lasota@interia.pl" },
    { name: "Mikołajczyk Mateusz", phone: "+48 573 058 135", email: "mateusz.orapi@gmail.com" },
    { name: "Orapi Biuro", phone: "+48 692 986 344", email: "biuro@orapi.com" },
    { name: "Płocieniczak Bartosz", phone: "+48 576 439 351", email: "b.plocieniczak.orapi@gmail.com" }
];
